import axios from "axios";
import { HOST } from "../host-config";
import { auth } from "../firebase";

export const getUserInfo = async (userId) => {

    const requestParams = {
      headers: {
        Authorization: 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImJhNjI1OTZmNTJmNTJlZDQ0MDQ5Mzk2YmU3ZGYzNGQyYzY0ZjQ1M2UiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmVjcnVpdG1lbnRidWRkeS1lZDRmMCIsImF1ZCI6InJlY3J1aXRtZW50YnVkZHktZWQ0ZjAiLCJhdXRoX3RpbWUiOjE3MTE2Mzc5MjgsInVzZXJfaWQiOiJuYlhCdTF1MnVaWWhRWXZVSWNEeElKVklaeDkyIiwic3ViIjoibmJYQnUxdTJ1WlloUVl2VUljRHhJSlZJWng5MiIsImlhdCI6MTcxMTYzNzkyOCwiZXhwIjoxNzExNjQxNTI4LCJlbWFpbCI6InJlY3J1aXRtZW50YnVkZHlAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInJlY3J1aXRtZW50YnVkZHlAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.FhnRzJ-Sm5aRL7iEbnE7Sqb5DekzeQtoLFiLnrGu7CrqLtQo2dmCpWp-5EFlqkTZfecv3To0HA8rZeAuXUUhjPjOpEnGD9giM-KcCT03f5a4rdD53guJS-ja5S-BldnzbyBqaNqcaPv7TnC_0Fo7MdNTSM8WIvRI74i-UioNigzpNgws5zKxBDa5G4J4-Qc7vpuMjrEex8g-eE9ssy5ex8iwT7OVXBzJq_ACGwTq9fXXPOhG_AHwyb5Fgjpf7cZmuCkzIb3Qhynzqg0-bXP8vAMDQ4Rz2oUebOSoOCA_U97RzWpuN0E4HHzbGtf91xEfO4_9Ob6ppIbOpODOAEqyIQ',
      },
    };

  
    return axios.get(HOST + "/api/users/" + userId, requestParams);
  };

export const updateUserInfo = async (userId, payload) => {

  const requestParams = {
    headers: {
      Authorization: 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImJhNjI1OTZmNTJmNTJlZDQ0MDQ5Mzk2YmU3ZGYzNGQyYzY0ZjQ1M2UiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmVjcnVpdG1lbnRidWRkeS1lZDRmMCIsImF1ZCI6InJlY3J1aXRtZW50YnVkZHktZWQ0ZjAiLCJhdXRoX3RpbWUiOjE3MTE2Mzc5MjgsInVzZXJfaWQiOiJuYlhCdTF1MnVaWWhRWXZVSWNEeElKVklaeDkyIiwic3ViIjoibmJYQnUxdTJ1WlloUVl2VUljRHhJSlZJWng5MiIsImlhdCI6MTcxMTYzNzkyOCwiZXhwIjoxNzExNjQxNTI4LCJlbWFpbCI6InJlY3J1aXRtZW50YnVkZHlAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInJlY3J1aXRtZW50YnVkZHlAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.FhnRzJ-Sm5aRL7iEbnE7Sqb5DekzeQtoLFiLnrGu7CrqLtQo2dmCpWp-5EFlqkTZfecv3To0HA8rZeAuXUUhjPjOpEnGD9giM-KcCT03f5a4rdD53guJS-ja5S-BldnzbyBqaNqcaPv7TnC_0Fo7MdNTSM8WIvRI74i-UioNigzpNgws5zKxBDa5G4J4-Qc7vpuMjrEex8g-eE9ssy5ex8iwT7OVXBzJq_ACGwTq9fXXPOhG_AHwyb5Fgjpf7cZmuCkzIb3Qhynzqg0-bXP8vAMDQ4Rz2oUebOSoOCA_U97RzWpuN0E4HHzbGtf91xEfO4_9Ob6ppIbOpODOAEqyIQ',
    },
  };

  return axios.put(HOST + "/api/users/" + userId, payload, requestParams)
};